name: E2E (Playwright)

on:
  workflow_call:


jobs:
  playwright-tests:
    timeout-minutes: 60
    strategy:
      matrix:
        shardIndex: [1,2,3,4]
        shardTotal: [4]
    name: E2E Playwright Testing ${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          fetch-depth: 0

      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c
        with:
          go-version: "1.24"
          cache-dependency-path: backend/go.mod

      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f
        with:
          node-version: lts/*

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

      - name: Install dependencies
        run: pnpm install
        working-directory: frontend

      - name: Install Go Dependencies
        run: go mod download
        working-directory: backend

      - name: Run E2E Tests
        run: task test:e2e -- --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        name: Upload partial Playwright report
        if: ${{ !cancelled() }}
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: frontend/blob-report/
          retention-days: 2

  merge-reports:
    # Merge reports after playwright-tests, even if some shards have failed
    if: ${{ !cancelled() }}
    needs: [playwright-tests]
    name: Merge Playwright Reports
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

      - name: Install dependencies
        run: pnpm install
        working-directory: frontend

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          path: frontend/all-blob-reports
          pattern: blob-report-*
          merge-multiple: true

      - name: Merge into HTML Report
        run: pnpm exec playwright merge-reports --reporter html,github ./all-blob-reports
        working-directory: frontend

      - name: Upload HTML report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: html-report--attempt-${{ github.run_attempt }}
          path: frontend/playwright-report
          retention-days: 30